default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { "localhost" } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch("CAPSTOQ_BACKEND_DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch('CAPSTOQ_BACKEND_DATABASE_PASSWORD') { "" } %>

development:
  <<: *default
  database: capstoq_backend_development

test:
  <<: *default
  database: capstoq_backend_test

production:
  <<: *default
  database: <%= ENV['CAPSTOQ_BACKEND_DATABASE'] %>
  username: <%= ENV['CAPSTOQ_BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['CAPSTOQ_BACKEND_DATABASE_PASSWORD'] %>
